name: "Godot -> Itch.io Web"
on: push

env:
  GODOT_VERSION: 4.1
  WORKING_DIR: gjf-gmtk-23

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Prep Build Directory
        run: mkdir html5
      - name: Web Build
        run: |
          mkdir -v -p build/web
          cd godot-project-dir
          godot -v --headless --export-release "WEB" ../build/web/index.html
      - name: Butler Upload
        uses: dulvui/itchio-butler-upload@v0.0.1
        with:
          working-directory: html5
          api-key: ${{ secrets.ITCH_IO_API_KEY }}
          user: ${{ secrets.ITCH_USER }}
          game: gjf-gmtk-23
          channel: html5
