name: "Godot -> Itch.io Web"
on: push

env:
  GODOT_VERSION: 4.1
  WORKING_DIR: gjf-gmtk-23

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p build/web
          cd gjf-gmtk-23
          godot -v --headless --export-release WEB ../build/web/index.html
