name: "Godot -> Itch.io Web"
on: push

env:
  GODOT_VERSION: 4.0.3
  WORKING_DIR: gjf-gmtk-23

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Prep Build Directory
        run: mkdir html5
      - name: Web Build
        uses: dulvui/godot-html-export@v0.0.2
        with:
          working-directory: $WORKING_DIR
          godot-version: 4.0.3
      - name: Butler Upload
        uses: dulvui/itchio-butler-upload@v0.0.1
        with:
          working-directory: html5
          api-key: ${{ secrets.ITCH_IO_API_KEY }}
          user: ${{ secrets.ITCH_USER }}
          game: gjf-gmtk-23
          channel: html5
